@TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImY3MTQyMjIwLTczNDEtNDc3Yy1iYWE1LTYxNTQzM2EwNmJmNiIsImlhdCI6MTc0NDc3NTk5MH0.7mDmrUMr4Gxe-57_Mkek1rfiAk_THrLzizURX3mgUdI
@BASEURL=http://localhost:3000/api/v1

###
# @name Login 
POST {{BASEURL}}/auth
accept: application/json
content-type: application/json

{
  "phone": "8787572702",
  "password": "123Clashofclan@"
}

###
# @name USER 
GET {{BASEURL}}/auth
accept: application/json
content-type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name Logout
POST {{BASEURL}}/auth/logout
accept: application/json
content-type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name Register 
POST {{BASEURL}}/auth/register
accept: application/json
content-type: application/json

{
  "email": "bimon@gmail.com",
  "name": "MON",
  "phone": "8837011018",
  "password": "123Clashofclan@"
}

###
# @name Dashboard 
GET {{BASEURL}}/dashboard
accept: application/json
content-type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name Update User Role
PATCH {{BASEURL}}/admin/role
accept: application/json
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
  "userId":"72df3f34-c591-4883-919b-2b81632d4274",
  "role":"SUPERADMIN"
}

###
# @name Get All Users 
GET {{BASEURL}}/admin/users
accept: application/json
content-type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name Get All parking 
GET {{BASEURL}}/parking?page=3
accept: application/json
content-type: application/json

###
# @name Get Parking By Id 
GET {{BASEURL}}/parking/a4d7b7e6-6f79-4f21-8ef0-d23b93445c93
accept: application/json
content-type: application/json

###
# @name GET All Parking Request 
GET {{BASEURL}}/partner
accept: application/json
content-type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name Create Parking Request 
POST {{BASEURL}}/partner
accept: application/json
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
  "description": "Secure parking with EV charging and easy access to public transport and dining options.",
  "userId":"72df3f34-c591-4883-919b-2b81632d4274"
}

###
# @name Create Parking 
POST {{BASEURL}}/parking
accept: application/json
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Greenview Parking Plaza",
  "address": "42 Elm Street, Midtown",
  "price": 6.5,
  "rating": ["c1a3d62e-b5f9-48be-bc0f-ea4dcae0db76", "5df02eb5-3a7f-45c4-9274-18d8679eb795"],
  "distance": "0.4 mi",
  "available": 17,
  "totalSpots": 80,
  "openHours": "5:00 AM - 11:00 PM",
  "description": "Secure parking with EV charging and easy access to public transport and dining options.",
  "image": "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?ixlib=rb-4.0.3",
  "status": "ACTIVE",
  "features": ["EV Charging", "Security", "CCTV", "Wheelchair Access"],
  "gallery": [
    "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?ixlib=rb-4.0.3",
    "https://images.unsplash.com/photo-1590674899484-13d6c7094a9f?ixlib=rb-4.0.3"
  ],
  "userId":"72df3f34-c591-4883-919b-2b81632d4274"
}
