@id = 1


### Add Version Update

POST {{NEXT_PUBLIC_API_URL}}/api/v1/kot-version?id={{id}} HTTP/1.1
Content-Type: application/json

{
  "additional_info": {
    "estimated_downtime": "0",
    "rollback_available": false
  },
  "author": "Release Bot",
  "description": [
    "Fix Search input icon",
    "Tynrai Jingrwai page",
    "Song Correction",
    "UI Update"
  ],
  "mandatory": true,
  "min_supported_version": "1.0.1",
  "platforms": [
    "android",
    "ios"
  ],
  "release_date": "2025-08-011T14:00:00Z",
  "release_notes_url": "https://jyrwaboys-v2.vercel.app/docs/release/kot-jingrwai",
  "title": "Stable Release",
  "version": "1.0.2"
}


### Get Update Info

GET {{NEXT_PUBLIC_API_URL}}/kot-version?id={{id}} HTTP/1.1
Content-Type: application/json


### Get No of user

PUT {{NEXT_PUBLIC_API_URL}}/kot-version HTTP/1.1
Content-Type: applicktion/json
