
###
# @name  Plans 
GET {{BASEURL}}/plan
accept: application/json
content-type: application/json

###
# @name  create plan 
POST {{BASEURL}}/admin/plans
accept: application/json
content-type: application/json

{
  "price": 58
}
